---
title: "data_wrangling"
author: "Lyuou Zhang"
date: "2/14/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rnoaa)
library(rvest)
library(httr)
library(jsonlite)
library(lubridate)
```

NOAA data: using Jeff's code

```{r}
# Get a list of all NY station IDs
stations <- ghcnd_stations()
nystationids <-  stations %>% 
  filter(state == "NY") %>% 
  distinct(id)

# Pull the desired weather data for all of these stations
nydat <- meteo_pull_monitors(nystationids$id, 
                             date_min = "2010-05-01", 
                             date_max = "2010-12-31", 
                             var = c("TMAX", "TMIN", 'TAVG'))


```

Pull data from API?


```{r}

station_url <- 'https://www.ncdc.noaa.gov/cdo-web/api/v2/stations'
station <- GET(url = station_url, add_headers())

key <- 'gueIeHeBhcidcWXyOLKQZHzKMlGwNQSq'

station <- ncdc_stations(token = key)
ny_station <- station$data %>% 
  as.tibble() 
```


```{r}

nydat_sub <- nydat %>% 
  filter(!is.na(tmax) & !is.na(tmin)) %>% 
  filter(date >= '2010-10-01' & date <= '2010-10-31') %>% 
  group_by(id) %>% 
  filter(id == 'USC00300183')

# 1. take the range of each day -> monthly average
nydat_sub <- nydat_sub %>% 
  mutate(diff = tmax - tmin)
mean(nydat_sub$diff)
# 119.9032

# 2. take the monthly mean of tmax and tmin and get the difference
mean(nydat_sub$tmax) - mean(nydat_sub$tmin)
# 119.9032

# 3. SD of the monthly average 
nydat_sub <- nydat_sub %>% 
  mutate(avg_temp = (tmax + tmin)/2)
sd(nydat_sub$avg_temp)
# 35.09231

```








