---
title: "quantile_reg"
author: "Erin Kawazu"
date: "3/25/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(quantreg)
library(ggplot2)

```

## Data import

```{r data importing}
# Birth
birth_data <- read_delim('./data/NYS_0717_groupby_CYM_OEGestWeekly.txt', delim = '\t') %>% 
  janitor::clean_names() %>%
  filter(is.na(notes)) %>%
  select(-notes) %>%
  mutate(
    county = str_replace(county, ' County, NY', ''),
    county_ym = str_c(county, year, month_code, sep = '-')
  )

# OLD NEW YORK WEATHER DATA
# nyc_temp_raw <- read.csv("./data/ny_temp_data.csv")
# nyc_temp <- nyc_temp_raw[!is.na(nyc_temp_raw["tmax"]),]
# nyc_temp$tmax <- nyc_temp$tmax/10
# nyc_temp$tmin <- nyc_temp$tmin/10

# Tempearture
ny_temp <- read.csv("./data/nydata_month.csv") %>% 
  janitor::clean_names() %>%
  select(-x) %>%
  mutate(year = as.character(year)) %>%
  unite("county_ym", county, year, month, sep = "-")
ny_temp$county <- tolower(ny_temp$county)

# Covariates
ses <- read.csv("./data/ses.csv")
county_names <- read.csv("./data/ny_counties.csv")

county_names$geoid <- county_names$X...fips
county_names <- county_names[c(2,3)]

covars <- merge(ses, county_names, by = "geoid")
colnames(covars)[colnames(covars)=="county_name"] <- "county"
covars$county <- tolower(covars$county)

# Other miscellaneous cleaning
trim.trailing <- function (x) sub("\\s+$", "", x)
covars$county <- trim.trailing(covars$county)

```

## Data cleaning and processing

```{r data cleaning and processing}
## Births (Categorical Count Data)
birth_count <- birth_data

birth_count$extreme_preterm <- ifelse(birth_count$oe_gestational_age_weekly_code < 28, birth_count$births, 0)
birth_count$v_preterm <- ifelse(birth_count$oe_gestational_age_weekly_code < 32 & birth_count$oe_gestational_age_weekly_code > 28, birth_count$births, 0)
birth_count$preterm <- ifelse(birth_count$oe_gestational_age_weekly_code < 37 & birth_count$oe_gestational_age_weekly_code > 32, birth_count$births, 0)
birth_count$normal <- ifelse(birth_count$oe_gestational_age_weekly_code >= 37, birth_count$births, 0)

county_births <- birth_count %>% 
  select(county_ym) %>% 
  unique()

extreme <- birth_count %>% group_by(county_ym) %>%
  summarize(t_extreme_preterm = sum(extreme_preterm)) 
very_p <- birth_count %>% group_by(county_ym) %>%
  summarize(t_v_preterm = sum(v_preterm))
preterm <- birth_count %>% group_by(county_ym) %>%
  summarize(t_preterm = sum(preterm))
normal <- birth_count %>% group_by(county_ym) %>%
  summarize(t_normal = sum(normal))

tot_count <- merge(county_births, extreme, by = "county_ym") %>% 
  merge(very_p, by = "county_ym") %>% 
  merge(preterm, by = "county_ym") %>% 
  merge(normal, by = "county_ym")

rm(extreme, very_p, preterm, normal) # Clean up

tot_count <- tot_count %>%
  separate(county_ym, c("county", "year", "month"), sep = "-", remove = FALSE)
tot_count$county <- tolower(tot_count$county)

#birth_covar <- merge(tot_count, covars, by = "county", all.x = TRUE)
### Does not work

## Births (Average Gestational Age in Weeks)
ges_age <- birth_data
ges_age <- ges_age %>% 
  mutate(tot = oe_gestational_age_weekly_code*births)

ges_age_data <- ges_age %>% group_by(county_ym) %>%
  summarize(avg_ges_age = sum(tot)/sum(births)) %>%
  separate(county_ym, c("county", "year", "month"), sep = "-", remove = FALSE) # Clean identifying variables
ges_age_data$county <- tolower(ges_age_data$county) # Make all lowercase

ges_covars <- merge(ges_age_data, covars, by = "county", all.x = TRUE) # Merged with covariates

ny_merged <- merge(ges_covars, ny_temp, by = "county_ym", all.x = TRUE) %>% 
  select(-X)

# plot(density(ges_age_data$avg_ges_age)) # Exploratory plot (two nodes)

```


## Data analysis

```{r data analysis}
quantile(ny_merged$avg_ges_age, c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9)) # Understand how the data look (the values of interest)

##

TauList <- seq(0.1, 0.9, by = 0.1)
TauList

qr.models  <- rq(avg_ges_age ~ sd_temp + without_hs + college + med_income + pop,
                 data = ny_merged, 
                 tau = TauList)

# Assemble estimates from each model

summary.qr.models <- summary(qr.models, alpha = 0.05)

Model10th   <- c(summary.qr.models[[1]]$coefficients[2,1:2])
Model20th   <- c(summary.qr.models[[2]]$coefficients[2,1:2])
Model30th   <- c(summary.qr.models[[3]]$coefficients[2,1:2])
Model40th   <- c(summary.qr.models[[4]]$coefficients[2,1:2])
Model50th   <- c(summary.qr.models[[5]]$coefficients[2,1:2])
Model60th   <- c(summary.qr.models[[6]]$coefficients[2,1:2])
Model70th   <- c(summary.qr.models[[7]]$coefficients[2,1:2])
Model80th   <- c(summary.qr.models[[8]]$coefficients[2,1:2])
Model90th   <- c(summary.qr.models[[9]]$coefficients[2,1:2])

# Create dataframe 

coeff.table <- rbind(Model10th, Model20th, Model30th, Model40th, Model50th, Model60th, Model70th, Model80th, Model90th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE)
coeff.table$LCI <- coeff.table$Value - coeff.table$`Std. Error`*1.96
coeff.table$UCI <- coeff.table$Value + coeff.table$`Std. Error`*1.96

# Set names for dataframe

names(coeff.table) <- c("coeff", "sterror", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("10th", "20th", "30th", "40th",
                               "50th", "60th", "70th", "80th", 
                               "90th"))

# Plot

fp.qr.models <- ggplot(data=coeff.table, # defines what dataset we are using
                  aes(x=ModelName,  # defines variable for the x axis
                      y=coeff,      # defines the variable for the point along the y axis
                      ymin=lci,     # defines the lower bound of the confidence interval
                      ymax=uci)) +  # define the upper bound of the confidence interval   
  geom_pointrange() +               # creates a point (y) with line defined by ymin and ymax        
  geom_errorbar()+                  # creates lines with bars
  geom_hline(aes(yintercept=0.0), lty=2) + # add a dashed line at y=0 
  xlab("Quantile of Interest") +              # labels for axes
  ylab(expression("Average Gestational Age (95% CI)"))

fp.qr.models
```

